const ACTION_MARK_SOLVED = "solved";
const ACTION_REPORT_BUG = "report_bug";
const SOLVED_EMOJI = "white_check_mark";
const INCIDENT_SEVERITY = "P1 - Critical";
const ORDER_MANAGEMENT_AREA = "Order Management";
const INCIDENT_CHANNEL = "C9RK0BLEP"; // #incidents
const EMERALD_CHANNEL = "C02JHHHKP5K";
const CHANNELS_TO_EXCLUDE = [
  // 'C012K7XU4LE', // #bot-testing
];
const CHANNELS_FOR_BUGS_WORKFLOW_REMINDER = [
  "C02E1D1G3B3", // #chr-test
  "C03N12SR0RK", // #product-questions
  "C07PRTJSD6G", // #product-bugs
];
const HOTJAR_RECORDING_CHANNEL = "C0BGS6HHV63"; // #amber-hotjar
const MAZE_RESPONSE_CHANNEL = "C0BHC6GEXC7"; // #amber-maze

module.exports = {
  ACTION_MARK_SOLVED,
  ACTION_REPORT_BUG,
  SOLVED_EMOJI,
  INCIDENT_SEVERITY,
  ORDER_MANAGEMENT_AREA,
  INCIDENT_CHANNEL,
  EMERALD_CHANNEL,
  CHANNELS_TO_EXCLUDE,
  CHANNELS_FOR_BUGS_WORKFLOW_REMINDER,
  HOTJAR_RECORDING_CHANNEL,
  MAZE_RESPONSE_CHANNEL,
};
