name: Keepalive Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "facilitate-incident-review.yml, next-on-call.yml, open-rfcs.yml, recently-published.yml, sapphire-on-call-retro.yaml, sapphire-on-call.yml, security-bounty-rotation.yml, standup-reminder.yml"
          time_elapsed: "0"
