name: Next On Call

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * MON,THU"

jobs:
  next-on-call:
    uses: artsy/duchamp/.github/workflows/incident-next-on-call.yml@main
    with:
      schedule-id: ${{ vars.INCIDENT_IO_SCHEDULE_ID }}
    secrets:
      incident-io-api-key: ${{ secrets.INCIDENT_IO_API_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
