name: Open RFCs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * MON,WED,FRI"

jobs:
  open-rfcs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run CLI
        id: cli
        run: echo "PAYLOAD=$(/home/runner/work/joule/joule/node_modules/.bin/artsy scheduled:rfcs)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Open RFCs > Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: ${{steps.cli.outputs.PAYLOAD}}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
