name: Standup Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: "43 13 * * MON"

jobs:
  standup-reminder:
    uses: artsy/duchamp/.github/workflows/incident-standup-reminder.yml@main
    with:
      schedule-id: ${{ vars.INCIDENT_IO_SCHEDULE_ID }}
    secrets:
      incident-io-api-key: ${{ secrets.INCIDENT_IO_API_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
